#!/usr/bin/env python3
"""Refresh a GitHub App installation token and write it to an env file.

Usage
-----

    # One-shot: print token to stdout
    python scripts/gh_app_token.py \
        --app-id 123456 \
        --installation-id 78901234 \
        --private-key /etc/autonoma/autonoma.private-key.pem

    # Write to an env-file for docker-compose to read
    python scripts/gh_app_token.py \
        --app-id "$APP_ID" \
        --installation-id "$INSTALL_ID" \
        --private-key /etc/autonoma/gh-app.pem \
        --env-file /etc/autonoma/gh.env

    # Daemon mode: refresh every 50 minutes (tokens live 60 min)
    python scripts/gh_app_token.py --daemon ...

Recommended: run as a sidecar in docker-compose with ``--daemon`` so the
API container can pick up ``GH_TOKEN`` via a shared volume / env file.
Tokens expire after 60 min, we refresh every 50 min to avoid races.

Secrets
-------
The PEM file must be readable only by the account running this script
(``chmod 0400``). The token itself is equally sensitive — treat the
env file the same way.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

logger = logging.getLogger("gh_app_token")


def _build_jwt(app_id: str, private_key_pem: str) -> str:
    """Sign a short-lived JWT the GitHub App API accepts.

    Uses PyJWT + cryptography (pip install pyjwt[crypto]). The JWT payload
    is the minimal one GitHub requires — iss=app_id, iat slightly in the
    past to tolerate clock skew, exp <= 10 min from now.
    """
    try:
        import jwt  # type: ignore
    except ImportError:
        sys.exit(
            "ERROR: PyJWT not installed. Run: pip install 'pyjwt[crypto]'"
        )
    now = int(time.time())
    payload = {
        "iat": now - 30,           # clock-skew tolerance
        "exp": now + 9 * 60,       # 9 minutes (GitHub max is 10)
        "iss": str(app_id),
    }
    return jwt.encode(payload, private_key_pem, algorithm="RS256")


def _request_installation_token(app_jwt: str, installation_id: str) -> dict[str, Any]:
    """POST to /app/installations/{id}/access_tokens and return the response body."""
    url = f"https://api.github.com/app/installations/{installation_id}/access_tokens"
    req = urllib.request.Request(
        url,
        method="POST",
        headers={
            "Authorization": f"Bearer {app_jwt}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "autonoma-gh-app",
        },
        data=b"",  # empty body requests default scopes/repos
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        sys.exit(
            f"ERROR: installation token request failed ({e.code}): {detail}"
        )


def _write_env_file(path: Path, token: str, expires_at: str) -> None:
    """Write an env file docker-compose / systemd can source.

    Format is plain ``KEY=value`` lines (no quotes), which matches both
    docker-compose ``env_file:`` and systemd ``EnvironmentFile=``.
    """
    body = (
        "# Auto-generated by scripts/gh_app_token.py — DO NOT EDIT MANUALLY\n"
        f"# expires_at={expires_at}\n"
        f"GH_TOKEN={token}\n"
    )
    # Atomic replace so a half-written file is never consumed mid-refresh.
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    os.chmod(tmp, 0o600)
    tmp.replace(path)


def refresh_once(args: argparse.Namespace) -> str:
    pem = Path(args.private_key).read_text(encoding="utf-8")
    app_jwt = _build_jwt(args.app_id, pem)
    resp = _request_installation_token(app_jwt, args.installation_id)
    token = resp["token"]
    expires_at = resp.get("expires_at", "unknown")
    if args.env_file:
        _write_env_file(Path(args.env_file), token, expires_at)
        logger.info(
            "wrote installation token to %s (expires %s)",
            args.env_file, expires_at,
        )
    else:
        print(token)
    return token


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-id", required=True)
    parser.add_argument("--installation-id", required=True)
    parser.add_argument(
        "--private-key",
        required=True,
        help="Path to the .pem private key downloaded from the App settings page.",
    )
    parser.add_argument(
        "--env-file",
        help="If set, write the token to this env file atomically. Otherwise print to stdout.",
    )
    parser.add_argument(
        "--daemon",
        action="store_true",
        help="Loop forever, refreshing every 50 minutes.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=args.log_level,
        format="[%(asctime)s] %(name)s %(levelname)s: %(message)s",
    )

    if not args.daemon:
        refresh_once(args)
        return

    # Daemon: refresh every 50 min. GitHub tokens expire in 60 min, so
    # 50 gives us a ~10 min buffer against slow cron / clock drift.
    INTERVAL = 50 * 60
    while True:
        try:
            refresh_once(args)
        except SystemExit:  # inner sys.exit from _request_installation_token
            raise
        except Exception:
            logger.exception("refresh failed; retrying in 60s")
            time.sleep(60)
            continue
        time.sleep(INTERVAL)


if __name__ == "__main__":
    main()
